# Gin-Vue-Admin Global Configuration

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[sector-migration]'
  director: '/var/log/sector-migration'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
# server config
system:
  # api-ip-valid: true